#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  launcher.py
#
#  Copyright 2014 Felix Haller <ich@ein-freier-mensch.de>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
import dbus
from dbus.mainloop.pyqt5 import DBusQtMainLoop


if __name__ == "__main__":

	try:
		bus_loop = DBusQtMainLoop(set_as_default=True)
		bus = dbus.SessionBus(bus_loop)
		launcher = bus.get_object("org.pygmy.launcher", "/org/pygmy/MainWindow")
		launcher.wakeup()
	except:
		import sys
		from PyQt5 import QtWidgets
		from core import Core, DBusObject
		print("launcher not running yet...")
		app = QtWidgets.QApplication(sys.argv)
		core = Core()
		launcher = DBusObject(core)
		launcher.wakeup()
		app.exec_()
		
